######################################################################
# Automatically generated by qmake (3.0) Thu May 2 16:58:27 2013
######################################################################

TEMPLATE = app
TARGET = glsl-tester
INCLUDEPATH += .
QT += widgets opengl
CONFIG += debug

# Input
HEADERS += glwidget.h
SOURCES += glwidget.cpp main.cpp
