######################################################################
# Automatically generated by qmake (3.0) Thu May 2 16:58:27 2013
######################################################################

TEMPLATE = app
TARGET = glsl-tester
INCLUDEPATH += .
QT += widgets opengl
CONFIG += 
QMAKE_CXXFLAGS += -lGL -DGL_GLEXT_PROTOTYPES
QMAKE_LDFLAGS += -lGL

# Input
HEADERS += src/glwidget.h src/window.h
SOURCES += src/glwidget.cpp src/main.cpp src/window.cpp
OBJECTS_DIR = objs/
MOC_DIR = src/
